import { useEffect, useState } from "react";
import { AlertTriangle, PauseCircle, Power, Radio, WifiOff } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { cn } from "@/lib/utils";
import { useEngine } from "@/lib/engine-store";
import type { LinkState } from "@/lib/api";

function uptimeLabel(since: number | null): string { if (!since) return "—"; const seconds = Math.max(0, Math.floor((Date.now() - since) / 1000)); const days = Math.floor(seconds / 86400); const hours = Math.floor((seconds % 86400) / 3600); const minutes = Math.floor((seconds % 3600) / 60); return days ? `${days}d ${hours}h` : hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function agoLabel(ts: number | null): string { if (!ts) return "no events"; const seconds = Math.max(0, Math.floor((Date.now() - ts) / 1000)); return seconds < 60 ? `${seconds}s ago` : seconds < 3600 ? `${Math.floor(seconds / 60)}m ago` : `${Math.floor(seconds / 3600)}h ago`; }
const TONE: Record<LinkState["status"], { dot: string; label: string; text: string }> = {
  online: { dot: "bg-primary", label: "Connected", text: "text-primary" }, connecting: { dot: "bg-accent", label: "Connecting", text: "text-accent" }, awaiting_qr: { dot: "bg-accent", label: "Scan QR", text: "text-accent" }, awaiting_code: { dot: "bg-accent", label: "Enter code", text: "text-accent" }, awaiting_password: { dot: "bg-amber-400", label: "Enter 2FA", text: "text-amber-300" }, paused: { dot: "bg-amber-400", label: "Flood paused", text: "text-amber-300" }, attention: { dot: "bg-amber-400", label: "Needs attention", text: "text-amber-300" }, error: { dot: "bg-destructive", label: "Error", text: "text-destructive" }, offline: { dot: "bg-muted-foreground", label: "Offline", text: "text-muted-foreground" },
};

export function StatusStrip() {
  const { snapshot, disconnect, streamOnline, saveSettings } = useEngine();
  const [, force] = useState<number>(0);
  useEffect(() => { const handle = setInterval(() => force((value) => value + 1), 1000); return () => clearInterval(handle); }, []);
  const link = snapshot?.link;
  const status = link?.status ?? "offline";
  const tone = TONE[status];
  const automationOn = snapshot?.settings.automationEnabled ?? false;
  const killed = snapshot?.settings.killSwitch ?? false;
  return <div className="sticky top-0 z-30 border-b border-white/[0.06] bg-background/80 backdrop-blur-xl"><div className="flex items-center gap-3 px-4 py-3 sm:px-6"><div className="flex min-w-0 items-center gap-2.5"><span className={cn("h-2.5 w-2.5 shrink-0 rounded-full", tone.dot, status === "online" && "animate-signal")} /><div className="min-w-0"><p className={cn("truncate text-sm font-semibold leading-tight", tone.text)}>{killed ? "Emergency stop" : tone.label}{link?.identity ? <span className="text-muted-foreground"> · {link.identity}</span> : null}</p><p className="truncate font-mono text-[10px] leading-tight text-muted-foreground">{link?.mode ?? "none"} · up {uptimeLabel(link?.since ?? null)} · event {agoLabel(link?.lastEventAt ?? null)}{streamOnline ? "" : " · feed reconnecting"}</p></div></div><div className="ml-auto flex items-center gap-2"><div className={cn("hidden items-center gap-2 rounded-full px-3 py-1.5 text-[11px] ring-1 sm:flex", automationOn && !killed ? "bg-primary/[0.07] text-primary ring-primary/20" : "bg-amber-400/[0.06] text-amber-300 ring-amber-400/20")}><span>{automationOn && !killed ? "Automation on" : "Automation off"}</span><Switch checked={automationOn && !killed} onCheckedChange={(checked) => saveSettings({ automationEnabled: checked, ...(checked ? { killSwitch: false } : {}) })} /></div>{status === "paused" ? <PauseCircle className="h-4 w-4 text-amber-300" /> : status === "error" || status === "attention" ? <AlertTriangle className="h-4 w-4 text-destructive" /> : null}<Button size="sm" variant={killed ? "default" : "outline"} className={cn("h-8 gap-1.5 rounded-full text-xs", killed && "bg-destructive text-white hover:bg-destructive/90")} onClick={() => saveSettings({ killSwitch: !killed })}><Power className="h-3.5 w-3.5" /><span className="hidden md:inline">{killed ? "Release stop" : "Emergency stop"}</span></Button><AlertDialog><AlertDialogTrigger asChild><Button size="sm" variant="ghost" disabled={status === "offline"} className="h-8 gap-1.5 rounded-full text-xs text-destructive hover:bg-destructive/10 hover:text-destructive">{status === "offline" ? <WifiOff className="h-3.5 w-3.5" /> : <Radio className="h-3.5 w-3.5" />}<span className="hidden sm:inline">Disconnect</span></Button></AlertDialogTrigger><AlertDialogContent className="border-white/[0.08] bg-card"><AlertDialogHeader><AlertDialogTitle>Drop the Telegram link?</AlertDialogTitle><AlertDialogDescription>The session is preserved, but no Telegram events or actions flow until reconnect. To pause workflows without unlinking, use the Automation switch.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="rounded-xl">Keep connected</AlertDialogCancel><AlertDialogAction className="rounded-xl bg-destructive text-white" onClick={() => disconnect()}>Disconnect now</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div></div>;
}
